// <auto-generated />
namespace Grupo_5_CE1_MN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CE01Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CE01Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202502270208278_CE01Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
